### ISSUE TITLE
Plugin does not work after installing

### ISSUE THREAD

**Issue by grumpyTofu** [grumpyTofu/nx-mongo-migrate#9]
**Describe the bug**
The plugin is not properly installable from npm

**To Reproduce**
follow the readme from a new empty project

**Current Output**
Readme steps fail

**Expected behavior**
Should be able to complete all steps listed in readme

**Environment (please complete the following information):**
 - 0.0.7
 - macOS

**Additional context**
NA

**Comment by grumpyTofu** [comment]
@erbilsilik I just posted a new version that includes esbuild to dynamically bundle your TS scripts & migration config. Please upgrade to latest and you should be use nx:migrate* commands to run your migrations now. I tested locally in a new project with a global shared migration config for simplicity and it was working. Can you test this with your multi-db setup and confirm if this is working?

**Comment by erbilsilik** [comment]
Thanks for the updates! 

@grumpyTofu still some issues:

1. I'm getting `Migrations not initialized in project. Please run the init generator first.` when I remove `migration.config` which is on the root directory (I may also fix this, it's probably because of the following code below)
```
if (!existsSync('migration.config.ts')) {
    throw new Error(
      'Migrations not initialized in project. Please run the init generator first.'
    );
  }
```

2. I want to use my the same Mongoose schema on migrations that I use for the application and also some internal libraries. However, I'm getting when trying to run nx executor commands.

`Cannot find module ‘@my-app/enums'`

**Comment by grumpyTofu** [comment]
Nice! You are correct, that is a good catch! I must have missed making the validation check on migration config dynamic. Easy fix though, there's already a method to dynamically get the path.


Esbuild should be able to bundle your code from other apps and libs as long as those paths are registered in your tsconfig settings. I am wondering if it is failing to get the correct tsconfig. Do you know if you have anything custom in any of your tsconfigs? If so, would you mind sharing redacted versions? Or have you kept it similar to the setup that nx provides out of the box?

**Comment by grumpyTofu** [comment]
@erbilsilik I was able to reproduce locally. I push a fix that should allow you to compile from other libraries within your Nx project. You will need to re-run the init generator. Let me know if this fixes the issue!

**Comment by erbilsilik** [comment]
@grumpyTofu Cool! Now, I'm getting error because it cannot find my configuration file. You can try something similar to the following (note:  this works when I use this package as my internal library).

```
import * as fs from 'fs';
import * as ini from 'ini';

import { MigrationConfigFactory } from ‘@my-package/mongo-migrate';
import { resolveSecrets } from ‘@my-package/resolve-secrets';
import { join } from 'path';

export async function resolveConfig() {
  const envFile = join(__dirname, `src/config/${process.env.NODE_ENV}.ini`);
  const { MONGODB_URI } = ini.parse(fs.readFileSync(envFile, 'utf-8'));
  return resolveSecrets({ MONGODB_URI });
}

const config: MigrationConfigFactory = async () => {
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const config: any = await resolveConfig();
  return {
    dbUri: config.MONGODB_URI,
    migrationCollection: 'migrations', // default
  };
};

export default config;


```

**Comment by grumpyTofu** [comment]
@erbilsilik I am guessing that your config is just not getting picked up by esbuild. I have not used `.ini` configuration files before. I think this might still work with `.env` but if you are using `.ini` then you would probably need programmatic access as a feature. Another option could be extending the project config to allow devs to specify a custom esbuild config so the config file also gets bundled in your build. Otherwise, it could be difficult to address all possible ways of configuring a project. 

Either way, I think I am going to close this issue since the recent changes allow the library to work in a relatively simple environment. I will open a separate issue for programmatic access and mark it as help wanted.
